import Header from "../components/header/Header"
import { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { Button, Container } from "react-bootstrap";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Criando o menu de navegação */}
      <Header />
      {/* adicionando o conteudo */}
      <main>
      <Container className="py-5 text-center">
          <h1 className="mt-5 display-1">
            A experiência de compra ideal para os amantes de <strong>Tecnologia</strong>.
          </h1>
          <p className="my-4">
            Nossos produtos são projetados para proporcionar uma experiência única e incomparável. Cada item é cuidadosamente selecionado para garantir qualidade, inovação e satisfação.
            Combinamos tecnologia de ponta com design elegante para oferecer produtos que não apenas atendem, mas superam as expectativas. Ao escolher nossos produtos, você está optando por
            excelência, durabilidade e um toque de exclusividade que transforma cada compra em uma experiência memorável. 
          </p>
          <Link href="/products">
            <Button variant="dark" className="px-4 pb-2">
              Conheça nossos produtos!
            </Button>
          </Link>
        </Container>
      </main>
    </>
  )}

export default Home